title: "해오름휴게소 · 포항서숲캠핑장"
baseurl: "/hyugeso-camping-hub"
description: "정육식당, 셀프세차장, 무인카페가 있는 휴게소와 오토캠핑장 소식 및 정보 모음"
theme: minima
lang: ko_KR
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
header_pages:
  - about-hyugeso.md
  - about-camping.md
google_site_verification: "nnSzzuu5anjhQdRPFt6VpxDeoZg-tP3egj83tjt_GoQ"
